FROM node:20-buster-slim

RUN apt-get -y update \
    && apt-get install -y git
RUN mkdir /app

WORKDIR /app

ENV NODE_PATH /app/node_modules/

COPY ./client/package*.json ./

ADD ./client ./

RUN npm install

EXPOSE 5173

CMD ["npm", "run", "dev"]
