services:
  client:
    container_name: jobly-ui
    build:
      context: .
      dockerfile: ./devops/Dockerfile.dev
    ports:
      - "5173:5173"
    env_file: .env.local
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:



